// src/git/diff-summary.ts — Generate Diff Summaries for PRs

import { execSync } from 'node:child_process';
import { resolve } from 'node:path';

/**
 * File change information
 */
export interface FileChange {
  path: string;
  linesAdded: number;
  linesRemoved: number;
}

/**
 * Diff summary statistics
 */
export interface DiffStats {
  filesChanged: number;
  linesAdded: number;
  linesRemoved: number;
  files: FileChange[];
}

/**
 * Complete diff summary
 */
export interface DiffSummary {
  stats: DiffStats;
  commits: string[];
  markdown: string;
}

/**
 * Execute git command safely
 */
function execGit(command: string, cwd?: string): string {
  try {
    const workDir = cwd ? resolve(cwd) : process.cwd();
    return execSync(command, {
      cwd: workDir,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch (error: unknown) {
    const err = error as { stderr?: Buffer; stdout?: Buffer; message?: string };
    const stdout = err.stdout?.toString('utf-8').trim() || '';
    // Return empty string for errors (e.g., no commits)
    return stdout;
  }
}

/**
 * Parse git diff --stat output
 */
function parseDiffStat(output: string): DiffStats {
  const lines = output.split('\n').filter((l) => l.trim().length > 0);
  const files: FileChange[] = [];
  let totalAdded = 0;
  let totalRemoved = 0;

  for (const line of lines) {
    // Skip summary line (e.g., "3 files changed, 42 insertions(+), 12 deletions(-)")
    if (line.includes('file') && (line.includes('changed') || line.includes('insertion') || line.includes('deletion'))) {
      continue;
    }

    // Parse file line: "path/to/file.ts | 42 +++++-----"
    const match = line.match(/^(.+?)\s+\|\s+(\d+)\s+([+-]+)$/);
    if (match) {
      const [, path, , changes] = match;
      const linesAdded = (changes.match(/\+/g) || []).length;
      const linesRemoved = (changes.match(/-/g) || []).length;

      files.push({
        path: path.trim(),
        linesAdded,
        linesRemoved,
      });

      totalAdded += linesAdded;
      totalRemoved += linesRemoved;
    }
  }

  return {
    filesChanged: files.length,
    linesAdded: totalAdded,
    linesRemoved: totalRemoved,
    files,
  };
}

/**
 * Parse git log output
 */
function parseCommits(output: string): string[] {
  if (!output || output.trim().length === 0) {
    return [];
  }
  return output.split('\n').filter((l) => l.trim().length > 0);
}

/**
 * Generate Markdown summary from diff stats and commits
 */
function formatMarkdown(stats: DiffStats, commits: string[], runId?: string): string {
  const lines: string[] = [];

  lines.push('## Changes (auto-generated by workbench)');
  lines.push('');

  // Files Modified
  lines.push('### Files Modified');
  if (stats.files.length === 0) {
    lines.push('- _No files modified_');
  } else {
    for (const file of stats.files) {
      const changes = file.linesAdded > 0 || file.linesRemoved > 0
        ? `(+${file.linesAdded}/-${file.linesRemoved})`
        : '';
      lines.push(`- \`${file.path}\` ${changes}`.trim());
    }
  }
  lines.push('');

  // Stats
  lines.push('### Stats');
  lines.push(`- Files changed: ${stats.filesChanged}`);
  lines.push(`- Lines added: ${stats.linesAdded}`);
  lines.push(`- Lines removed: ${stats.linesRemoved}`);
  lines.push('');

  // Commits
  if (commits.length > 0) {
    lines.push('### Commits');
    for (const commit of commits) {
      lines.push(`- ${commit}`);
    }
    lines.push('');
  }

  // Run Info
  if (runId) {
    lines.push('### Run Info');
    lines.push(`- Run ID: ${runId}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate a diff summary between two branches
 * @param branch - Target branch
 * @param baseBranch - Base branch to compare against
 * @param cwd - Optional working directory
 * @param runId - Optional run ID to include in summary
 * @returns Complete diff summary with Markdown
 */
export function generateSummary(
  branch: string,
  baseBranch: string,
  cwd?: string,
  runId?: string
): DiffSummary {
  // Get diff stats
  const diffStatOutput = execGit(`git diff --stat ${baseBranch}...${branch}`, cwd);
  const stats = parseDiffStat(diffStatOutput);

  // Get commit log
  const logOutput = execGit(`git log --oneline ${baseBranch}..${branch}`, cwd);
  const commits = parseCommits(logOutput);

  // Generate Markdown
  const markdown = formatMarkdown(stats, commits, runId);

  return {
    stats,
    commits,
    markdown,
  };
}
