// src/git/__tests__/diff-summary.test.ts

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { execSync } from 'node:child_process';
import { generateSummary } from '../diff-summary.js';

// Mock execSync
vi.mock('node:child_process', () => ({
  execSync: vi.fn(),
}));

const mockedExecSync = vi.mocked(execSync);

describe('diff-summary', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  it('should parse diff stat correctly', () => {
    // Mock git diff --stat output
    mockedExecSync.mockImplementation((command) => {
      if (typeof command === 'string' && command.includes('git diff --stat')) {
        return `src/file1.ts | 42 +++++++++++++++++++++++
src/file2.ts | 15 ++++-----
2 files changed, 45 insertions(+), 12 deletions(-)
`;
      }
      if (typeof command === 'string' && command.includes('git log')) {
        return 'abc123 Add feature\n';
      }
      return '';
    });

    const summary = generateSummary('feature-branch', 'main');

    expect(summary.stats.filesChanged).toBe(2);
    expect(summary.stats.linesAdded).toBeGreaterThan(0);
    expect(summary.stats.linesRemoved).toBeGreaterThan(0);
    expect(summary.stats.files).toHaveLength(2);
    expect(summary.stats.files[0].path).toBe('src/file1.ts');
    expect(summary.stats.files[1].path).toBe('src/file2.ts');
  });

  it('should parse git log correctly', () => {
    // Mock outputs
    mockedExecSync.mockImplementation((command) => {
      if (typeof command === 'string' && command.includes('git diff --stat')) {
        return 'src/file.ts | 10 ++++++++++\n1 file changed, 10 insertions(+)\n';
      }
      if (typeof command === 'string' && command.includes('git log')) {
        return `abc123 Add feature
def456 Fix bug
789ghi Refactor code
`;
      }
      return '';
    });

    const summary = generateSummary('feature-branch', 'main');

    expect(summary.commits).toHaveLength(3);
    expect(summary.commits[0]).toBe('abc123 Add feature');
    expect(summary.commits[1]).toBe('def456 Fix bug');
    expect(summary.commits[2]).toBe('789ghi Refactor code');
  });

  it('should generate correct Markdown format', () => {
    // Mock outputs
    mockedExecSync.mockImplementation((command) => {
      if (typeof command === 'string' && command.includes('git diff --stat')) {
        return 'src/test.ts | 5 +++++\n1 file changed, 5 insertions(+)\n';
      }
      if (typeof command === 'string' && command.includes('git log')) {
        return 'abc123 Test commit\n';
      }
      return '';
    });

    const summary = generateSummary('feature-branch', 'main', undefined, 'run-123');

    expect(summary.markdown).toContain('## Changes (auto-generated by workbench)');
    expect(summary.markdown).toContain('### Files Modified');
    expect(summary.markdown).toContain('`src/test.ts`');
    expect(summary.markdown).toContain('### Stats');
    expect(summary.markdown).toContain('Files changed: 1');
    expect(summary.markdown).toContain('Lines added:');
    expect(summary.markdown).toContain('Lines removed:');
    expect(summary.markdown).toContain('### Commits');
    expect(summary.markdown).toContain('abc123 Test commit');
    expect(summary.markdown).toContain('### Run Info');
    expect(summary.markdown).toContain('Run ID: run-123');
  });

  it('should handle empty diff correctly', () => {
    // Mock empty outputs
    mockedExecSync.mockImplementation((command) => {
      if (typeof command === 'string' && command.includes('git diff --stat')) {
        return ''; // No changes
      }
      if (typeof command === 'string' && command.includes('git log')) {
        return ''; // No commits
      }
      return '';
    });

    const summary = generateSummary('feature-branch', 'main');

    expect(summary.stats.filesChanged).toBe(0);
    expect(summary.stats.linesAdded).toBe(0);
    expect(summary.stats.linesRemoved).toBe(0);
    expect(summary.stats.files).toHaveLength(0);
    expect(summary.commits).toHaveLength(0);
    expect(summary.markdown).toContain('_No files modified_');
  });
});
