// src/memory/auto-memory.ts — Automatic Memory Storage After Agent Runs

import type { RunResult, Message } from '../types/index.js';
import type { AgentLoopHooks } from '../runtime/agent-loop.js';
import type { SessionStorage } from '../storage/session-storage.js';
import type { RunLogger } from '../storage/run-logger.js';
import type { UserConfig } from '../config/user-config.js';
import type { LanceDBMemoryStore } from './lancedb-store.js';
import { summarizeSession } from './session-summarizer.js';
import type { MemoryEntry } from '../types/memory.js';

/**
 * Configuration for auto-memory hook
 */
export interface AutoMemoryConfig {
  /** Session storage to retrieve messages */
  sessionStorage: SessionStorage;
  
  /** Run logger to retrieve metadata and update memoryId */
  runLogger: RunLogger;
  
  /** Memory store to save summaries */
  memoryStore: LanceDBMemoryStore;
  
  /** User configuration for autoSummarize setting */
  userConfig: UserConfig;
  
  /** CLI flag override: if true, skip summarization */
  noSummarize?: boolean;
}

/**
 * Create an AgentLoopHooks.onAfterRun hook that automatically:
 * 1. Checks if summarization is enabled (via UserConfig + CLI flag)
 * 2. Summarizes the session using summarizeSession()
 * 3. Generates embedding for the summary
 * 4. Stores as Memory in LanceDB
 * 5. Updates RunMetadata with memoryId
 * 
 * @param config - Auto-memory configuration
 * @returns onAfterRun hook function
 * 
 * @example
 * ```ts
 * const hooks: AgentLoopHooks = {
 *   onAfterRun: createAutoMemoryHook({
 *     sessionStorage,
 *     runLogger,
 *     memoryStore,
 *     userConfig,
 *     noSummarize: options.noSummarize,
 *   }),
 * };
 * 
 * const runtime = new AgentLoop(..., hooks);
 * ```
 */
export function createAutoMemoryHook(config: AutoMemoryConfig): AgentLoopHooks['onAfterRun'] {
  return async (result: RunResult, context: { runId: string }) => {
    try {
      // 1. Check if summarization is enabled
      const shouldSummarize = shouldAutoSummarize(config);
      
      if (!shouldSummarize) {
        return; // Skip summarization
      }

      // 2. Check minimum message count
      const session = await config.sessionStorage.load(result.sessionId);
      const minMessages = config.userConfig.minMessagesForSummary ?? 3;
      
      if (session.messages.length < minMessages) {
        console.warn(`[auto-memory] Skipping summarization: session has only ${session.messages.length} messages (min: ${minMessages})`);
        return;
      }

      // 3. Load run metadata
      const runLog = await config.runLogger.loadRun(context.runId);
      if (!runLog) {
        console.warn(`[auto-memory] Could not load run metadata for run ${context.runId}`);
        return;
      }

      // 4. Extract modified files from tool calls (heuristic: look for write_file, edit_file calls)
      const filesModified = extractModifiedFiles(runLog.toolCalls);

      // 5. Summarize session
      const summary = await summarizeSession({
        sessionId: result.sessionId,
        runId: context.runId,
        messages: session.messages as Message[],
        runMetadata: runLog.metadata,
        filesModified,
      });

      // 6. Create MemoryEntry (embedding will be generated by LanceDBMemoryStore)
      const memoryEntry: MemoryEntry = {
        id: `session-${result.sessionId}-${Date.now()}`,
        type: 'session',
        content: summary.summary,
        summary: summary.summary.substring(0, 200), // First 200 chars as summary
        tags: extractTagsFromSummary(summary),
        source: {
          type: 'session',
          sessionId: result.sessionId,
          runId: context.runId,
        },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        metadata: {
          sessionId: summary.sessionId,
          runId: summary.runId,
          keyDecisions: summary.keyDecisions,
          errors: summary.errors,
          learnings: summary.learnings,
          relatedFiles: summary.relatedFiles,
          tokenUsage: summary.metadata.tokenUsage,
          status: summary.metadata.status,
          timestamp: summary.metadata.timestamp,
          messageCount: session.messages.length,
        },
      };

      // 7. Save to memory store (embedding will be auto-generated)
      await config.memoryStore.init();
      const savedMemory = await config.memoryStore.add(memoryEntry);

      // 8. Update RunMetadata with memoryId (reload-before-update to avoid race conditions)
      const freshRunLog = await config.runLogger.loadRun(context.runId);
      if (freshRunLog) {
        freshRunLog.metadata.memoryId = savedMemory.id;
        await config.runLogger.updateRunMetadata(context.runId, freshRunLog.metadata);
      } else {
        console.warn(`[auto-memory] Could not reload run log ${context.runId} for metadata update`);
      }

      console.error(`✅ [auto-memory] Saved summary to memory: ${savedMemory.id}`);

    } catch (error) {
      // ⚠️ IMPORTANT: Summarization failures should NOT crash the agent run
      // Log as warning and continue
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.warn(`⚠️ [auto-memory] Failed to create session summary: ${errorMessage}`);
      // Don't re-throw, just log warning
    }
  };
}

/**
 * Determine if auto-summarization should run
 * Checks UserConfig + CLI flag override
 */
function shouldAutoSummarize(config: AutoMemoryConfig): boolean {
  // CLI flag --no-summarize takes precedence
  if (config.noSummarize === true) {
    return false;
  }

  // Check UserConfig (default: true)
  return config.userConfig.autoSummarize ?? true;
}

/**
 * Extract modified files from tool calls
 * Looks for write_file, edit_file, apply_patch tool calls
 */
function extractModifiedFiles(toolCalls: Array<{ toolName: string; input: Record<string, unknown> }>): string[] {
  const modifiedFiles = new Set<string>();
  const fileWriteTools = ['write_file', 'edit_file', 'apply_patch'];

  for (const call of toolCalls) {
    if (fileWriteTools.includes(call.toolName)) {
      const path = call.input.path as string | undefined;
      if (path && typeof path === 'string') {
        modifiedFiles.add(path);
      }
    }
  }

  return Array.from(modifiedFiles);
}

/**
 * Extract tags from SessionSummary
 * Combines key concepts from decisions, errors, and learnings
 */
function extractTagsFromSummary(summary: {
  keyDecisions: string[];
  errors: string[];
  learnings: string[];
  relatedFiles: string[];
}): string[] {
  const tags = new Set<string>();

  // Add 'session' as base tag
  tags.add('session');

  // Extract keywords from decisions (simple heuristic: first word)
  summary.keyDecisions.forEach((decision) => {
    const words = decision.toLowerCase().split(/\s+/);
    if (words.length > 0 && words[0].length > 2) {
      tags.add(words[0]);
    }
  });

  // Add 'error' tag if errors were encountered
  if (summary.errors.length > 0) {
    tags.add('error');
  }

  // Add 'learning' tag if learnings were extracted
  if (summary.learnings.length > 0) {
    tags.add('learning');
  }

  // Add file extension tags from modified files
  summary.relatedFiles.forEach((file) => {
    const ext = file.split('.').pop();
    if (ext && ext.length > 0 && ext.length < 5) {
      tags.add(ext);
    }
  });

  // Limit to 10 tags
  return Array.from(tags).slice(0, 10);
}
